FROM python:3.12-alpine

ENV FLASK_APP regalias/src/app.py
ENV FLASK_RUN_HOST 0.0.0.0
# ENV DB_HOST=localhost
# ENV DB_NAME=regalias
# ENV DB_USER=semard
# ENV DB_PASSWORD=semard

WORKDIR /regalias

RUN apk add --no-cache gcc musl-dev linux-headers

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . ./regalias

CMD ["flask", "run"]
