version: "3"

networks:
  main:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: regalias
      POSTGRES_USER: semard
      POSTGRES_PASSWORD: semard123
    ports:
      - "5433:5432"
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - main

  emqx:
    image: emqx/emqx:latest
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    networks:
      - main

  api-regalias:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_NAME: regalias
      DB_USER: semard
      DB_PASSWORD: semard123
      MQTT_HOST: emqx
    ports:
      - "4000:4000"
    networks:
      - main
    depends_on:
      - postgres
      - emqx

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www/:/var/www/certbot/:ro
    depends_on:
      - api-regalias
    networks:
      - main

  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw
  #   depends_on:
  #     - nginx
  #   networks:
  #     - main
