FROM python:3.12-alpine

ENV FLASK_APP Regalias_Back/src/app.py
ENV FLASK_RUN_HOST 0.0.0.0

WORKDIR /Regalias_Back

RUN apk add --no-cache gcc musl-dev linux-headers

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . ./Regalias_Back

CMD ["python", "Regalias_Back/src/app.py"]
