FROM python:3.18-alpine

RUN apk add --no--cache python3-dev \
    && pip3 install --upgrade pip

WORKDIR /regalias

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . /regalias

RUN pip3 --no-cache-dir install -r requirements.txt

CMD ["flask", "run"]